### ISSUE TITLE
Roadmap do projeto

### ISSUE THREAD

**Issue by brunapinos** [BOSS-BigOpenSourceSister/BigSister#101]
Roadmap criado com a ferramenta Miro. Link para edição encontra-se no drive.
[BOSS Roadmap.pdf](https://github.com/BOSS-BigOpenSourceSister/BigSister/files/5367262/BOSS.Roadmap.pdf)

**Comment by carolinaferreira** [comment]
@brunapinos eu gostei bastante, só ficou um pouco sem qualidade mas é questão do miro na versão free
