### ISSUE TITLE
Entrevista: Cibersegurança

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#102]
# Informações básicas

- [x] **Entrevistada**: Priscila Kin Yamamoto Joranhezon
- [x] **Entrevistadoras**: Marina e Rafaella
- [x] **Backstage**: Carla
- [x] **Data**: 28/10
- [x] **Horário**: 20:00

# Preparação

## Criação do roteiro 
Para começar o roteiro, crie uma cópia do [template de roteiro](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/talk_like_a_boss/template_roteiro_entrevistas.md). 

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [ ] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [ ] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [ ] Criar o vídeo para a transmissão no youtube
- [x] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [ ] Texto base + informações específicas
- [ ] Arte do vídeo
- [ ] Link do vídeo

# Durante a entrevista

## 30 min de preparação
- [ ] Apresentar a ferramenta de transmissão para todas envolvidas
- [ ] Repassar o roteiro
- [ ] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [ ] Seguir o roteiro
- [ ] Podem conversar, sintam-se confortáveis
- [ ] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [ ] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [ ] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by Joranhezon** [comment]
Falar com mentoradas para serem entrevistadoras

**Comment by Joranhezon** [comment]
A nóssa próxima entrevista vai ser no dia 28/10/2020 às 19:30. Nessa talk, falaremos com a Priscila Kin Joranhezon sobre cibersegurança.

A "Talk like a Boss" é uma série de entrevistas, parte da iniciativa BOSS - Big Open Source Sister. O objetivo da "Talk like a Boss" é trazer mulheres inspiradoras para falar um pouco sobre seu trabalho, atuação e contribuições na comunidade de software livre.

Não perde o link: https://www.youtube.com/watch?v=4tqn_jzapyI

![Azul,_Roxo_e_Branco_Escolas_Aprendizado_Remoto_16_9_Vídeo_11](https://user-images.githubusercontent.com/20938170/96941034-c6108f00-14a7-11eb-8ec3-ab624dac0728.png)

**Comment by Joranhezon** [comment]
[Pergunta] Quando se fala de cibersegurança se pensa muito em segredos e "coisas escondidas". Essa afirmação é correta?

**Comment by Joranhezon** [comment]
[Pergunta] É possível ter cibersegurança em um contexto de Open Source?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Como posso manter meus dados e minhas contas seguras?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Tem algum jeito seguro de mandar nudes?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Quais são os riscos caso uma empresa que eu sou cliente tenha dados de clientes vazados?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Como me defender de golpes e proteger meus dados?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Com quais dados meus, devo me preocupar? Como cuidar deles?

**Comment by Thais-ra** [comment]
[Sugestão de pergunta]
Como você começou a atuar com segurança da informação? Oq você indica pra quem tem interesse na área?

**Comment by RochaCarla** [comment]
Sugere ferramentas para computadores pessoais para proteçao dos dados?

**Comment by RochaCarla** [comment]
Quais as habilidades técnicas alguém que trabalhe com segurança da informação? Qual conhecimento técnico? Quais as habilidades não técnicas?
