### ISSUE TITLE
Evento de Fechamento

### ISSUE THREAD

**Issue by carolinaferreira** [BOSS-BigOpenSourceSister/BigSister#108]
- [x] Marcar dia e horário (verificar a diponbilidade da galera)
- [x] Fazer texto de convite do evento
- [x] Fazer apresentação com toda retrospectiva e highlights do programa
- [x]  Fazer a arte do evento(@naiieandrade )
- [ ] Falar com as mentoradas para pegar depoimentos em video e editar pro dia;(@naiieandrade)
- [ ] Definir programação (2h30)
   - [ ] Retrospectiva
      - [ ] pegar depoimentos das little sisters sobre experiência na BOSS(@clarissalimab)
      - [ ] pegar endereço e tamanho da camiseta das mentoradas por meio de google forms(@Joranhezon);
      - [ ] mentoras devem elencar conquistas das mentoradas para apresentarmos(@todas)
      - [ ] pegar dados sobre commits (gráfico de commits, de PRs, de issues, etc.)(@dehatanes )
      - [ ] resumir os pontos positivos elencados na jamboard em um slide(@dehatanes )
   - [x] Dinâmica Secreta @clarissalimab 
   - [ ] Momento motivação / open mic(@naiieandrade )
   - [ ] Festenhas
- [ ] Festa a fantasiiiaaaa
- [ ] Gerar códigos do bolão[@dehatanes @RochaCarla]

HH e Among Us/Gartic!

**Comment by Joranhezon** [comment]
Acho que os destaques de cada mentorada pode ser cada mentora que fica responsável. E ai as outras se quiserem podem sugerir, etc.

**Comment by BrunaNayara** [comment]
Acho que poderia ser com tema de haloween, fantasias e coisas de terror

**Comment by Joranhezon** [comment]
MEU DEUS @BrunaNayara SIM POR FAVOR SIM

**Comment by naiieandrade** [comment]
Amei a ideia de se fantasiar para a festa de despedida ahhaha

**Comment by dehatanes** [comment]
O dia do evento ficou: 15/11/2020

**Comment by Joranhezon** [comment]
Lista de pessoas que vão dividir o valor total do bolão:
- Marina;
- Debs;
- Claris;

**Comment by BrunaNayara** [comment]
Ficou no domingo???? @dehatanes

**Comment by naiieandrade** [comment]
> O dia do evento ficou: 15/11/2020

Não é dia 13/11? Sexta-feira 13 o dia do fechamento? @BrunaNayara @dehatanes ?

**Comment by dehatanes** [comment]
@BrunaNayara @naiieandrade é dia 13 mesmo, eu que viajei e escrevi 15 errado hahahaha já editei meu comentário, valeu pelo toque 😬
