### ISSUE TITLE
Entrevista: "LGPD"

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSister/BigSister#110]
# Informações básicas

- [x] **Entrevistada**: Camila Teixeira
- [ ] **Entrevistadoras**: A definir
- [x] **Backstage**: @BrunaNayara 
- [ ] **Data**: A definir (entre 26 e 30 de outubro)
- [x] **Horário**: 19:00 às 21:00 (live das 19:30 às 20:30)

# Preparação

## Criação do roteiro 
Para começar o roteiro, crie uma cópia do [template de roteiro](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/talk_like_a_boss/roteiro_entrevistas.md). 

- [ ] Informações das entrevistadas: Nome e mini bio.
- [ ] Coletar perguntas acerca do tema abordado
- [ ] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [ ] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [ ] Criar o vídeo para a transmissão no youtube
- [ ] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [ ] Texto base + informações específicas
- [ ] Arte do vídeo
- [ ] Link do vídeo

# Durante a entrevista

## 30 min de preparação
- [ ] Apresentar a ferramenta de transmissão para todas envolvidas
- [ ] Repassar o roteiro
- [ ] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [ ] Seguir o roteiro
- [ ] Podem conversar, sintam-se confortáveis
- [ ] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [ ] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [ ] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
- O que é a LGPD? Qual a importância?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergutnta]**
- Devo me preocupar com meus dados? E porquê?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergutnta]**
- Como posso estar em conformidade com a lei e tomar cuidado com os dados dos meus clientes?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Qual a melhor maneira de identificar o titular dos dados em um atendimento por telefone/mensagem para evitar vazamento de dados? Ou seja, como garantir que está lidando com o titular dos dados?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
A LGPD fala que o titular tem que consentir para que a empresa possa ter acesso e possa fazer tratamento dos dados. Mas a maioria das redes ou dos serviços tem um termo de uso/serviço enorme e mesmo quea pessoa leia, se ela quer usar o serviço ela precisa aceitar os termos na totalidade. Tem alguma forma do titular não consentir com o tratamento dos dados pessoais?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Tem algum órgão ou agência reguladora que controlam o uso/tratamento dos dados feitos pela empresa??
Se o titular sentir que o direito está sendo ferido, quem o titular procura??

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Cap 2 e art 9  fala que o titular tem que ter acesso às infos do tratamento dos dados. Como o titular pode saber de forma clara ao que tá sendo feito com seus dados. Ele deve pedir ao controlador/operador dos dados? De que forma?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
De que forma o operado/controlador dos dados pode ser transparente quanto às infos sobre o tratamento?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Farmácias pedem acesso ao CPF para dar desconto, mas já aconteceu dos planos de saúde/seguro de vida terem acesso a esses dados e cobrarem mais caro do titrular. Você conhece algum caso que isso foi provado e foi pra justiça/ Qual foi o resultado?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
A lei fala da prote,cào de dados. O que a gente como usuário pode fazer para proteger os nossos dados de forma mais efetiva e como criar consciência da necessidade de proteção?

O que a gente como empresa..

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Quais dados as empresas podem apagar e a efetividade disso? Exemplo google e facebook: vc vai deixar de existir?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Os dados financeiros também são regulados pela LGPD? Pq uma instituição financeira que eu não tenho vínculo me ligou oferecendo serviços pq sabiam da minha renda e da possibilidade de crédito e quando eu pedi a exclusão ela disse que não poderia fazer isso, mas poderia marcar para que eu não recebesse mais ligação daquele banco. Os bancos podem fazer esse compartilhamento?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]** 
Quando a empresa tem uma falha de segurança e os dados dos usuários são vazados, o titular pode acionar a justiça e pedir algum tipo de reparação?

**Comment by naiieandrade** [comment]
**[Sugestão de pergunta]**
Quais são os dados mínimos obrigatórios que eu como consumidora tenho que dar? Porque por exemplo, tem lugar que pede cpf, rg, telefone, nome completo, data de nascimento... E se eu não quiser fornecer esses dados? Quais dados eu sou obrigada a falar para o serviço e quais posso ter a escolha de não falar? Depende do serviço?
