### ISSUE TITLE
Apresentação IEEE

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#115]

**Comment by BrunaNayara** [comment]
Já comecei a apresentação. Quem tiver acesso, pode ver aqui: https://docs.google.com/presentation/d/1Yf3mR0MI4xwDlqbOrNOdt4pcEeL24Dpez3QoPOzmpHU/edit?usp=sharing 

Quem não tiver e quiser ver, me chama

**Comment by BrunaNayara** [comment]
Apresentadíssimo
