### ISSUE TITLE
Challenge - GNOME (Fase 2)

### ISSUE THREAD

**Issue by RafaellaJunqueira** [BOSS-BigOpenSourceSister/BigSister#118]
## Checklist do documento - GNOME
Essa issue é para dividirmos os tópicos do documento que deve ser feito para submissão no desafio. Coloque seu nome na frente da parte que deseja fazer - ou que gostaria de dar ideias sobre como fazer - e atualize no [documento do drive](https://docs.google.com/document/d/17QzkiqPj0OS2fRRzWwAk6irMrsk6zU3xF4vuBSFs_wM/edit#heading=h.xz6mtaik3ymn).

### Tópicos

- [ ] Phase Two Guidelines
- [ ] Submission Criteria
- [ ] SUBMISSION BOSS
   - [ ] General Information 
   - [ ] Project
   - [ ] Explain any changes in project scope
   - [ ] Marketing/outreach plan for attracting users
   - [ ] Elements to encourage FOSS contributions
   - [ ] Milestones (@brunapinos )
   - [ ] Estimated Budget 
   - [ ] Human Resource Requirements
   - [ ] Deliverables (entregáveis)
   - [ ] Risks
   - [ ] Key performance indicators (indicadores)
   - [ ] Constraints (@Joranhezon )
        - [ ] Anticipate growing  (post-mortem)
        - [ ] Share with us

**Comment by BrunaNayara** [comment]
Acho que essa aí fechou
