### ISSUE TITLE
Material - Como rodar o projeto localmente?

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSister/BigSister#15]

**Comment by fabiolamfleury** [comment]
Podemos utilizar os arquivos do boilerplate (que já automatizam alguns comandos)https://github.com/lappis-unb/rasa-ptbr-boilerplate

Ou passar o passo-a-passo, como o da própria documentação do rasa, pra explicar um pouco mais detalhadamente como funciona rodar o projeto (treinar, atualizar, definir onde vai ser a saída, outras configurações)

https://rasa.com/docs/rasa-x/installation-and-setup/deploy/  (teria que ser traduzido)

**Comment by BrunaNayara** [comment]
Essa tarefa não foi feita nessa edição da boss. Tem intersecção com essa tarefa #14
