### ISSUE TITLE
Fazer Questionario de Disponibilidade

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#36]

**Comment by BrunaNayara** [comment]
Fazer enquete no telegram com os horários depois das 18:30

**Comment by dehatanes** [comment]
Opa, vi essa issue agora depois de muito tempo. 
Eu acho que podemos fechá-la porque no final das contas decidimos permanecer com as reuniões às segundas 19h mesmo :)
