### ISSUE TITLE
Estudar a possibilidade de Podcast

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#39]

**Comment by RochaCarla** [comment]
@BOSS-BigOpenSourceSister/mentoras

**Comment by Joranhezon** [comment]
Acho que podemos fechar essa issue já que ontem fizemos o primeiro [Talk Like a BOSS](https://www.youtube.com/watch?v=VLYOrJexZGI&t=40s).
