### ISSUE TITLE
Criar Instagram do BOSS

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#41]
- Compartilhar usuario e senha no grupo de mentoras.

**Comment by carolinaferreira** [comment]
@naiieandrade vc fez essa?

**Comment by naiieandrade** [comment]
> @naiieandrade vc fez essa?

**Comment by RochaCarla** [comment]
@BOSS-BigOpenSourceSister/mentoras
