### ISSUE TITLE
Tutorial de integração Jitsi + youtube

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSister/BigSister#42]

**Comment by naiieandrade** [comment]
Eu fiz aqui um passo a passo no gist. Se quiser posso colocar com imagens depois. @RochaCarla se puder dar uma olhada :eyes:

**Comment by RochaCarla** [comment]
Massa @naiieandrade .. to pegando o seu como referencia e vou adicionando as imagens :P

**Comment by Joranhezon** [comment]
Funciona perfeitamente :)
