### ISSUE TITLE
Discutir a viabilidade e possíveis atividades para encorajar engajamento da comunidade

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#48]
Discutir na reunião do dia 01/09.

Objetivo: Engajar mentoras e mentoradas para criar um ambiente de comunidade colaborativo.

**Comment by Joranhezon** [comment]
Pontos para serem considerados:
- Se é viável; 
- Frequência;
- Como será feito(Dinâmicas, jogos, atividades de desenvolvimento, etc);
- Se iremos fazer apenas no chatbot ou trazer as meninas das outras frentes também(Ou se faremos um por grupo);

**Comment by Joranhezon** [comment]
Sugestões:
- Fazermos atividades variadas semanalmente, com intuitos diferentes;
- Separar as pessoas em grupos e realizar dojos para desenvolver algo simples;
- Dinâmicas;
- Separar as pessoas em rodas de conversa sobre um assunto específico;

**Comment by naiieandrade** [comment]
Sugestão 1: Promover divisão entre as mentorandas para atividades sobre o tema ou relacionado.
Exemplo, no tema de chatbot (que é amanhã), iniciar com a divisão de 2 grupos para que elas discutam - o que é chatbot pra elas, qual experiência que já tiveram com chatbot, uma experiência boa e ruim e o que diferenciou as experiências. Isso em 15 minutos. No retorno do link da chamada oficial, 1/2 representantes de cada grupo falar o que foi levantado e a @brunapinos começar o conteúdo e citar o que foi falado por elas.

**Comment by naiieandrade** [comment]
Sugestão 2: Dividi-las em grupos (2 ou 3) para que pesquisem repositório que gostariam de contribuir em um futuro, ou ideias de criação de um, como aquele do Meme, dos filmes, de música... Algo para que aconteça o processo de pesquisar repositórios, ver projetos que existem e que gostem, criar um com alguma ideia que gostem e que as meninas do grupo começassem a contribuir em conjunto. A ideia não é a criação de um projeto/repo de big projetos (inicialmente), mas algum que elas possam compartilhar algo, informações, ferramentas a partir de um assunto em comum por grupo.

**Comment by naiieandrade** [comment]
Sugestão 3: Assim como a @Joranhezon disse, propor atividades semanais também onde elas fazem pareamento e vá alternando com objetivos semanais: pesquisar algum assunto e trazer, realizar pesquisas quantitativas/qualitativas, propor ideias/soluções de algo ...
