### ISSUE TITLE
Entrevista: "Documentação, escrita técnica e outreachy"

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSister/BigSister#49]
# Informações básicas

- [X] **Entrevistada**: Anna
- [X] **Entrevistadoras**: @giovanadionisio  e @Joranhezon 
- [X] **Backstage**: @BrunaNayara 
- [X] **Data**: 12/09/2020
- [X] **Horário**: 15:00 (início 15:30)

# Preparação

## Criação do roteiro 
Para começar o roteiro, crie uma cópia do [template de roteiro](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/talk_like_a_boss/roteiro_entrevistas.md). 

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [x] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [x] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [x] Criar o vídeo para a transmissão no youtube
- [x] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [x] Texto base + informações específicas
- [x] Arte do vídeo (Tá no grupo)
- [x] Link do vídeo (https://youtu.be/QgcXR94SMtA)

> Nessa talk, falaremos com a Anna, organizadora do Outreachy e mantenedora da documentação técnica do Open Collective.
A "Talk like a Boss" é uma série de entrevistas, parte da iniciativa BOSS - Big Open Source Sister. O objetivo da "Talk like a Boss" é trazer mulheres inspiradoras para falar um pouco sobre seu trabalho, atuação e contribuições na comunidade de software livre.

# Durante a entrevista

## 30 min de preparação
- [x] Apresentar a ferramenta de transmissão para todas envolvidas
- [x] Repassar o roteiro
- [x] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [x] Seguir o roteiro
- [x] Podem conversar, sintam-se confortáveis
- [x] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [x] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [x] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by BrunaNayara** [comment]
Sugestões de perguntas podem ser feitas como comentários nessa issue

**Comment by BrunaNayara** [comment]
@fabiolamfleury @clarissalimab @brunapinos  tem sugestões de perguntas?

**Comment by dehatanes** [comment]
**[Sugestão de perguntas]**

Uma pergunta sobre o assunto que eu vejo ser muito recorrente é: em que língua a documentação principal deveria ser escrita (nativo/inglês)?

Caso tenha a sugestão de escrever a doc em ambas as línguas: há alguma dica de como manter ambas as docs atualizadas e consistentes?

**Comment by dehatanes** [comment]
**[Sugestão de pergunta]**

Como justificar para pessoas que não são do time de engenharia o tempo investido e a priorização de tarefas de documentação? Sinto que muitas vezes as docs acabam sendo negligenciadas porque não separam tempo nas sprints para que elas sejam trabalhadas propriamente.

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**

Quais são as melhore práticas para ter uma documentação não-técnica(de comunidade) que vai ser mantida por muitas pessoas?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Como foi sua trajetória no Outreachy? Pq resolveu se inscrever?

**Comment by BrunaNayara** [comment]
@Joranhezon se quiser alterar o roteiro, manda ver. Ele tá aqui :D
Não esquece de deixar atualizado e mandar o link atualizado pra Giovana e pra Anna também
https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/master/talk_like_a_boss/roteiros/doc_outreachy_anna.md

**Comment by BrunaNayara** [comment]
@Joranhezon o link do vídeo do youtube é esse aqui https://youtu.be/QgcXR94SMtA
O que está no README tá errado.

**Comment by BrunaNayara** [comment]
Mini bio para adicionar no roteiro: 

Anna e só é organizadora do Outreachy — programa de estágios em comunidades de software livre — e mantenedora da documentação técnica do Open Collective. No passado, ela foi estagiária da comunidade Wikimedia pelo mesmo programa de estágio que hoje organiza, atuou como wikimedista-em-residência no MediaLab/UFG no projeto Tainacan e como especialista em projetos abertos no LAPPIS/UnB durante a tradução da brochura de expert da campanha "Dinheiro Público Código Público" da Free Software Foundation Europe. Ela também foi uma das primeiras escritoras técnicas a participar do Google Season of Docs.

**Comment by Joranhezon** [comment]
Tópicos para próximas entrevistas:
- Acessibilidade na tecnologia;
-  Organização e processos;

**Comment by BrunaNayara** [comment]
A entrevista foi um sucesso. Foi fechar a issue :D
