### ISSUE TITLE
Entrevista: "Maratonas de programação"

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSister/BigSister#52]
# Informações básicas

- [x] **Entrevistada**: Giovanna Kobus
- [x] **Entrevistadoras**: Mylena
- [x] **Backstage**: @RochaCarla 
- [x] **Data**: 10/09/2020
- [x] **Horário**: 14:00

# Preparação

## Criação do roteiro 

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [x] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [x] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [x] Criar o vídeo para a transmissão no youtube
- [x] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [x] Texto base + informações específicas
- [x] Arte do vídeo
- [x] Link do vídeo

# Durante a entrevista

## 30 min de preparação
- [x] Apresentar a ferramenta de transmissão para todas envolvidas
- [x] Repassar o roteiro
- [x] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [x] Seguir o roteiro
- [x] Podem conversar, sintam-se confortáveis
- [x] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [x] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [x] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by BrunaNayara** [comment]
_Esse roteiro é específico para entrevista. Fiquem a vontade para customizar as perguntas. Sugerimos que, com antecedência, ele seja lido em conjunto e conversado com todas as participantes (entrevistadoras e entrevistadas). Lembrem-se de sempre dar espaço para todos as envolvidas falarem; um jeito de fazer isso é definindo previamente quem fala o quê._ 

> Seria interessante falar tudo com o gênero feminino, pois somos uma comunidade que todas as protagonistas são mulheres, além disso estamos falando para outras mulheres da comunidade ou que estão conhecendo e querendo fazer parte.


# Introdução 
**[Entrevistadora 1]** Cumprimentar quem tá assistindo;

## Se apresentarem:
**[Entrevistadora 1]** “Sou Entrevistada 1 e sou tal coisa” 

**[Entrevistadora 2]** “e eu sou a Entrevistada 2 e sou tal coisa”

## Apresentar a entrevista
**[Entrevistadora 2]** Falar um pouco sobre a entrevista:
- Conhecer as pessoas entrevistadas;
- Compartilhar experiências;
- Falar que vão ter mais entrevistas com temas diferentes
- Pedir para se inscreverem no canal para não perder nenhum episódio e compartilhar o vídeo com mais mulheres. 
- Lembrar que o contato e referências estarão na descrição do vídeo
- Avisar que as pessoas podem deixar suas perguntas e comentários no chat;	

**[Entrevistadora 1]** Falar o que é o tema

Apresentar a entrevistada:
“Hoje vamos falar com a:  **Entrevistada 1**. Ela é **mini bio**"


# Conhecendo a pessoa
**[Entrevistadora 1]** O que não tem no seu linkedin e você quer contar pra gente?

**[Entrevistadora 2]** Pergunta 2

# Mais sobre o tema
**[Entrevistadora 1]** Pergunta 1
**[Entrevistadora 2]** Pergunta 2
**[Entrevistadora 1]** Pergunta 3
**[Entrevistadora 2]** Pergunta 4

# Dicas e sugestões
**[Entrevistadora 1]** Pergunta 1
**[Entrevistadora 2]** Pergunta 2

# Encerramento

## Espaço para a entrevistada dar últimos recados, falar das redes sociais
Deixar o espaço livre

##  Informações finais

**[Entrevistadora 1]** Agradece a audiência. Curte, compartilha blablablablabla
**[Entrevistadora 2]** Informar da próxima entrevista (12 de setembro) sobre "_documentação, escrita técnica e outreachy_". E falar que teremos mais infos nas redes sociais.

**Comment by Joranhezon** [comment]
- Qual é o conhecimento que você considera mais importante para maratonas? E o mais inutil?
- Se você encontrasse a si mesma mais nova, iniciando sua jornada em maratonas, que dica se daria?

**Comment by BrunaNayara** [comment]
Sente muita diferença entre competir em time e competir sozinha nas jams? Quais os prós/contras de cada um?

**Comment by dehatanes** [comment]
Quais são os fatores que considera para decidir se vai se inscrever em uma maratona ou não?

**Comment by mylenar** [comment]
- Qual foi a sua maior dificuldade quando você começou a participar das maratonas?

**Comment by RochaCarla** [comment]
Que tipo de habilidade você desenvolve estudando/treinando para maratona de programação?

**Comment by BrunaNayara** [comment]
@mylenar muito obrigada pela condução da entrevista hoje <3
