### ISSUE TITLE
Criar guia de boas práticas da Mentora

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#64]
Criar um documento guia para boas práticas de mentoras da BOSS. A idéia é que seja utilizado para que novas mentoras tenham um ponto de partida para entender.

**Comment by BrunaNayara** [comment]
Sugestões de leitura para criar o guia:  
- https://www.radicalcandor.com/effective-one-on-ones/ 
- https://www.small-improvements.com/blog/24-questions-ask-next-11-meeting/ 
- https://www.small-improvements.com/blog/remote-work-feedback-questions/

**Comment by Joranhezon** [comment]
Colocar sobre formulários e como eles devem ser mandados sempre, mesmo que não ocorra 1:1.
