### ISSUE TITLE
Entrevista: "Mentorias e Tech Leaders"

### ISSUE THREAD

**Issue by giovanadionisio** [BOSS-BigOpenSourceSister/BigSister#69]
# Informações básicas

- [x] **Entrevistada**: Renata Soares e Camila Maciel
- [x] **Entrevistadoras**: @mariav-flor e @giovanadionisio 
- [x] **Backstage**: @RochaCarla e @RafaellaJunqueira 
- [x] **Data**: 23/09
- [X] **Horário**: 19:00

# Preparação

## Criação do roteiro 
Roteiro: https://github.com/BOSS-BigOpenSourceSister/BigSister/pull/72

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [x] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [X] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [X] Criar o vídeo para a transmissão no youtube
- [x] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [x] Texto base + informações específicas
- [x] Arte do vídeo
- [x] [Link do vídeo](https://www.youtube.com/watch?v=YQMH11KXDCA&feature=youtu.be)

> A nossa próxima entrevista é nessa quarta-feira, dia 23/09/2020, às 19h. Nessa talk, falaremos com a Camila Maciel, Tech Lead no QuintoAndar, e com Renata Soares, desenvolvedora também no QuintoAndar. Elas vão falar sobre desafios da carreira na área de Tecnologia, mentorias e liderança. 
> 
> A "Talk like a Boss" é uma série de entrevistas, parte da iniciativa BOSS - Big Open Source Sister. O objetivo da "Talk like a Boss" é trazer mulheres inspiradoras para falar um pouco sobre seu trabalho, atuação e contribuições na comunidade de software livre.

# Durante a entrevista

## 30 min de preparação
- [x] Apresentar a ferramenta de transmissão para todas envolvidas
- [x] Repassar o roteiro
- [x] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [ ] Seguir o roteiro
- [ ] Podem conversar, sintam-se confortáveis
- [ ] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [ ] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [ ] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by BrunaNayara** [comment]
Texto base:

A nóssa próxima entrevista vai ser no <dia da semana>, dia <dd/mm/aaaa> às <hh:mm>. Nessa talk, falaremos com a <pessoa 1> e <pessoa 2> sobre <tema>

A "Talk like a Boss" é uma série de entrevistas, parte da iniciativa BOSS - Big Open Source Sister. O objetivo da "Talk like a Boss" é trazer mulheres inspiradoras para falar um pouco sobre seu trabalho, atuação e contribuições na comunidade de software livre.

Não perde o link: <link>

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Qual o papel das pessoas líderes e lideradas na cultura inclusiva da equipe?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Qual o papel da pessoa tech lead?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Como aproveitar melhor os momentos de 1:1 e sair com bons pontos de ação para ter bons resultados?

**Comment by dehatanes** [comment]
**[Sugestão de pergunta]**
Qual seria um conselho que você daria a pessoas que serão as primeiras Tech Leads mulheres dentro da empresa delas?

**Comment by dehatanes** [comment]
**[Sugestão de pergunta]**
Já houve um conflito com seus liderados que acredita que o motivo ou desfecho teria sido diferente se não fosse pelo seu gênero? E com líderes pares?
Como lidou na época e como isso impactou na sua forma de liderar?

**Comment by BrunaNayara** [comment]
**Bio** 
Camilla Maciel, 27 anos e está há 4 no QuintoAndar, hoje é Lead Software Engineer. Gosta muito da ideia de liderar um time de engenheiros, ajudando em suas carreiras e guiando-os a resolver problemas reais com tecnologia de qualidade, sempre colocando a mão na massa.

**Comment by BrunaNayara** [comment]
**[Sugestao de pergunta]**

Como a pessoa liderada pode tirar melhor proveito das 1:1s?

**Comment by BrunaNayara** [comment]
**Bio da Renata**

Renata Soares, tenho 23 anos, sou formada em Engenharia de Software na UnB e trabalho como desenvolvedora há 3 anos (2 deles no Quinto Andar). Atualmente trabalho com programação funcional em clojure no time do financeiro.

pode adicionar que eu trabalhei 1 ano na secretaria de educação do df como desenvolvedora
e que participei das maratonas de programação na faculdade

**Comment by Joranhezon** [comment]
Quais seus maiores desafios como Tech Lead? Eles são técnicos ou de gerência?

**Comment by BrunaNayara** [comment]
Arrasaram
