### ISSUE TITLE
Entrevista: Síndrome da impostora: o que a Psicologia explica?	

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#73]
# Informações básicas

- [x] **Entrevistada**: Juliana Aguiar
- [x] **Entrevistadoras**: @mariav-flor e @estheraragaos
- [x] **Backstage**: @RochaCarla 
- [x] **Data**: 07/10/2020 - Quarta-feira
- [x] **Horário**: 19:30h

# Preparação

## Criação do roteiro 
Para começar o roteiro, crie uma cópia do [template de roteiro](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/talk_like_a_boss/roteiro_entrevistas.md). 

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [x] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [x] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [x] Criar o vídeo para a transmissão no youtube
- [x] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [x] Texto base + informações específicas
- [x] Arte do vídeo
- [x] Link do vídeo

# Durante a entrevista

## 30 min de preparação
- [x] Apresentar a ferramenta de transmissão para todas envolvidas
- [x] Repassar o roteiro
- [x] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [x] Seguir o roteiro
- [x] Podem conversar, sintam-se confortáveis
- [x] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [ ] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [ ] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by Joranhezon** [comment]
Fazer divulgacao braba, não pode esquecer.

**Comment by carolinaferreira** [comment]
- jeitos de abordar a síndrome do impostor, como acompanhar isso?

**Comment by BrunaNayara** [comment]
Sobre as entrevistadoras: A ideia era trazer alguém que parrticipou e organizou a anterior pra ajudar a guiar a novata na próxima. Já chamaram a Flor pra ver se ela topa?

**Comment by Joranhezon** [comment]
A @carolinaferreira pediu pra participar dessa, ai achamos que não teria problema. Ai nessa podemos chamar a Flor ou a Giovana e na próxima voltar a isso de rodízio de mentoradas.

**Comment by carolinaferreira** [comment]
Posso participar no staff pra acompanhar também só, o que acham? E aí as meninas assumem os papéis de entrevistadoras

**Comment by BrunaNayara** [comment]
A Gio já foi em duas seguidas. Aí acho que pode ser a Flor com a Carol se ela puder, senão, podemos puxar outra :D

**Comment by mariav-flor** [comment]
Gente, acham que é uma boa mudar o nome para "Síndrome da Impostora: O que a Psicologia explica?", tendo em vista que nosso público é majoritariamente feminino (nessa edição).

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
É síndrome da impostora ou eu de fato não tenho qualificação pra isso?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Quais fatores externos influenciam para essa percepção?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Tem algo que eu possa fazer para começar a me perceber mais merecedora das minhas realizações?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Como meus comportamentos/atitudes podem ser culpados pela sídrome da impostora de outra pessoa?

**Comment by BrunaNayara** [comment]
**[Sugestão de pergunta]**
Tem alguma coisa que posso fazer para ajudar outras pessoas? E a mim mesma?

**Comment by Joranhezon** [comment]
@mariav-flor acho super válido! Boa!

**Comment by Joranhezon** [comment]
**[Sugestão de pergunta]**
Existem grupos em que  a sindrome do impostor é mais presente? Quais são eles?

**Comment by Joranhezon** [comment]
**[Sugestão de pergunta]**
Existe alguma estimativa do quanto a sindrome do impostor afeta nas decisões e, em geral, na vida de uma pessoa?

**Comment by RafaellaJunqueira** [comment]
> Gente, acham que é uma boa mudar o nome para "Síndrome da Impostora: O que a Psicologia explica?", tendo em vista que nosso público é majoritariamente feminino (nessa edição).

Eu acho que pra essa edição, em específico, é válido já que as coisas estão todas voltadas para o público feminino, né?

**Comment by RafaellaJunqueira** [comment]
**[Sugestão de pergunta]**
O que podemos fazer no dia a dia para evitar pensamentos de autossabotagem?

**Comment by RafaellaJunqueira** [comment]
**[Sugestão de pergunta]**
O que fazer quando eu identificar que estou me desqualificando?

**Comment by RafaellaJunqueira** [comment]
**[Sugestão de pergunta]**
Como diferenciar comportamentos de uma "fase ruim" daqueles típicos da síndrome do impostor?

**Comment by mariav-flor** [comment]
A próxima edição da Talk Like a Boss é nesta quarta-feira, dia 07/10/2020, às 19:30h. Nessa talk, falaremos com a Juliana Aguiar, neuropsicóloga e mestre em neurociências do comportamento sobre o tema “Síndrome da Impostora: o que a Psicologia explica?”.

A ideia é discutir um pouco sobre o que é a síndrome da impostora e, em especial, de que forma ela a afeta as minorias, público-alvo da BOSS. Apesar de bastante relevante e comum, a síndrome da impostora nem sempre recebe a atenção devida no meio da Tecnologia, e pode até ser tratada como um mito. 

Com a ajuda da Juliana vamos entender as causas mais comuns para esse problema, como se manifestam os sentimentos de autodepreciação e inferioridade ilusória e como as pessoas, em especial as que fazem parte de grupos desprivilegiados, podem trabalhar para a reversão desses pensamentos.

Parte da Iniciativa BOSS - Big Open Source Sister, a "Talk like a Boss" é uma série de entrevistas cujo objetivo é trazer mulheres inspiradoras para falar um pouco sobre seu trabalho, atuação e contribuições para comunidade de software livre, bem como sobre temas correlatos à área de Tecnologia e minorias sociais.

 Não perde o link: https://www.youtube.com/watch?v=NzvxaDmyRpc

Quem é nossa convidada?
 
Juliana Aguiar é neuropsicóloga e mestre em neurociências do comportamento. Formada em Psicologia e mestre também pela UnB. Atualmente, trabalha no Hospital da Criança de Brasília José de Alencar e em clínica, nos quais realiza avaliação neuropsicológica e de psicodiagnóstico.

**Comment by RochaCarla** [comment]
Tem alguma forma de identificar minha síndrome da impostora? e alguma técnica para combater?
