### ISSUE TITLE
Checkpoint 22/09

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#74]
Pontos Positivos:
-  Acompanhamento aproximado é um diferencial na BOSS;
- Pareamento foi positivo e destravou problemas durante a execução da atividade;
-  Fazer a parte prática no conteúdo da semana (durante ou até mesmo depois da parte teórica);
- Aquele joguinho de descontração que rolou pós pareamento aproximou as meninas entre si e comigo também;
- A ideia de talks foi excelente;
- A ideia de pareamento foi muito boa, vi que minha mentorada estava pareando não só para realizar a tarefa da semana, mas porque elas quiseram tentar fazer outra coisa juntas;
- Compartilhar as gravações das reuniões no youtube.

Pontos a Melhorar:
- Me parece que muitas mentoradas estão desanimadas e até sumidas;
- Falta de comunicação não só entre as mentoradas, mas entre as mentoras;
- Falta de nivelamento no ingresso da mentoria;
- O não padrão das escolhas de mentoradas em relação ao grupo subrepresentado que queriamos atingir;
-  Padronização de na disponibilização dos materiais;
- Ritmo do projeto, falta de "mão na massa";
- Os 1:1s frequentes são bons por um lado para fazer o acompanhamento, mas por outro acontecem muitas repetições (de uma semana pra outra não muda muita coisa);
- Generalizar a BOSS pra contemplar mais minorias;
- Acho que as meninas estão desanimadas. Tem pouca interação no grupo do telegras;
- Senti falta de ser mais contextualizada no começo do projeto;
- Ta meio parado mesmo, acho que as meninas ficam muito "soltas".

Ações:
- Não prometer o que não podemos fazer;
- Colocar objetivos claros para a próxima semana no 1:1, mas também entender que algumas perguntas vão ser repetitivas;
- Definir ao certo o formato do 1:1, mas com possibilidade de colocar seu toque pessoal;
- Criar quiz para que as mentoradas fiquem em contato com o conteúdo da semana por fora do momento da aula e do 1:1;
- Anotar coisas que achamos que possa ser básicas, mas que acabam que não são;
- Contextualizar melhor as mentoras;
- Onboarding das mentoras;
- Conteúdo de Onboarding;

Dúvidas:
- Como abordar certos assuntos na síndrome do impostor?

Postmortem:
- Precisamos organizar melhor as atividades que vamos realizar durante o período da BOSS, talvez por milestones.(Escreve isso lá pra gente @RafaellaJunqueira ? :smile: );
- Discutir sobre frentes da BOSS;

**Comment by RafaellaJunqueira** [comment]
Pode deixar, vou atualizar lá!

**Comment by BrunaNayara** [comment]
@RafaellaJunqueira já atualizou né? Se tiver atualizado, fecha essa issue pra nós <3 ?
