### ISSUE TITLE
Criar newsletter semanal para divulgar conteúdo da BOSS

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSister/BigSister#82]
Avisos semanais com o cronograma detalhado da semana e o que será realizado de atividade. Também vale a pena colocar link de cada conteúdo citado.

Sugestão de datas de envio:

- [x] 05/10/2020 (Parabenizando todo o caminho e introduzir essas quatro últimas semanas de hand's on e muita contribuição)
- [x] 19/10/2020 (Parabenizando todo o caminho e lembrar as 2 últimas semanas de hand's on e que dá tempo ainda de contribuir) 
- [ ] 02/11/2020 (Um overview de todo o programa)

**Comment by BrunaNayara** [comment]
@naiieandrade te marquei pq você tinha comentado sobre criar os emails para esse mês de outubro

**Comment by BrunaNayara** [comment]
**Sugestão para o próximo email:**

Estamos em outubro a Hacktober Fest começou.

Não sabe o que é hacktober fest? É um evento da digital ocean pra estimular pessoas a contribuirem com projetos de software livre.
Estimular como? No final do mês, se você tiver mandado PR (contribuições) para algum projeto, eles mandam uns mimos (adesivos, camisetas...)
No github se você procurar em algum projeto legal de software livre que você conhece, pode ser que você ache issues com a label "Hacktoberfest". Isso quer dizer que aquelel projeto está esperando contribuições :D

Se vocês quiserem ler mais sobre isso, só dar um pulinho aqui nesse site: https://hacktoberfest.digitalocean.com/

Nós já organizamos o nosso conteúdo pensando nisso. Então organizamos algumas issues pra vocês dentro do boilerplate (colocar o link). A ideia é que seguindo as nossas próximas semanas, vocês á consigam mandar os PRs necessários para ganhar os mimos (os dias de blogueira vêm hahaha) . 

Então, acompanhem as próximas semanas, mandem dúvidas, mandem PRs, vamos tentar levar esses brindes pra casa!!!

**Comment by naiieandrade** [comment]
**Com base na sua sugestão @BrunaNayara** 

Heyy, estamos entrando na 9ª semana da BOSS! Já se passaram dois meses desde que tivemos nosso primeiro encontro, lembram?:cry: Com muita alegria parabenizamos todas vocês que chegaram até aqui, e desejamos mais forças ainda para essas semanas finais! 

<img alt="gif" src="https://media.giphy.com/media/YJ5OlVLZ2QNl6/giphy.gif"/>

Vocês aprenderam muita coisa! E nessas quatro últimas semanas teremos mais tempo de por a mão na massa e contribuir com projetos! Uhuul! Além do mais, estamos em outubro e a Hacktober Fest começou.

Não sabe o que é hacktober fest? É um evento da Digital Ocean pra estimular pessoas a contribuírem com projetos de software livre.
Estimular como? No final do mês, se você tiver mandado PR (contribuições) para algum projeto, eles mandam uns mimos (adesivos, camisetas...) :heart_eyes: 
No github se você procurar em algum projeto legal de software livre que você conhece, pode ser que você ache issues com a label "Hacktoberfest". Isso quer dizer que aquele projeto está esperando contribuições :D

Se vocês quiserem ler mais sobre isso, é só dar um pulinho aqui nesse site: https://hacktoberfest.digitalocean.com/

Nós já organizamos o nosso conteúdo pensando nisso. Então organizamos algumas issues pra vocês dentro do boilerplate (https://github.com/BOSS-BigOpenSourceSister/rasa-ptbr-boilerplate). A ideia é que seguindo as nossas próximas semanas, vocês já consigam mandar os PRs necessários para ganhar os mimos (os dias de blogueira virão hahaha) .

Então, acompanhem as próximas semanas, mandem dúvidas, mandem PRs, vamos tentar levar esses brindes pra casa!!!

Vamos sim ou vamos claro?

<img alt="gif" src="https://media.giphy.com/media/XtGTdywir49va/giphy.gif" />

**Comment by BrunaNayara** [comment]
@naiieandrade amei. Por mim, tá ótimo

**Comment by naiieandrade** [comment]
**Para o dia de hoje, 19/10/2020** 

Heyy, estamos quase chegando ao fim dessa iniciativa linda que começou há mais de 2 meses :crying_cat_face: ! Já fez a sua retrospectiva e o quanto você aprendeu desde o começo? Em uma breve retrospectiva aprendemos sobre linux, git, gitflow, docker, python, arquitetura, chatbot, rasa, boilerplate, comunidades, contribuição em projetos open source! E mais que isso colocamos muito a mão na massa! 

Faltam duas semanas para o fim da Hacktoberfest! É preciso 4 PRs em repositórios com as labels da #hacktoberfest! Se não contribuiu ainda tem tempo! Só se organizar e dar um gás esses últimos dias, se for preciso chame alguém para parear <3

<img alt="gif" src="https://media.giphy.com/media/L3otr7vJRYsJ6xrQxg/giphy.gif"/>


Nós já organizamos o nosso conteúdo pensando nisso. Então organizamos algumas issues pra vocês dentro do boilerplate (https://github.com/BOSS-BigOpenSourceSister/rasa-ptbr-boilerplate). A ideia é que seguindo as nossas próximas semanas, vocês já consigam mandar os PRs necessários para ganhar os mimos (os dias de blogueira virão hahaha) .

Então, acompanhem as próximas semanas, mandem dúvidas, mandem PRs, vamos tentar levar esses brindes pra casa!!!

Vamos sim ou vamos claro?

<img alt="gif" src="https://media.giphy.com/media/SO4trEzzGYDhC/giphy.gif" />

**Comment by Joranhezon** [comment]
Vale a pena comentar que estamos organizando uma despedida e falar que essa semana vai rolar o checkpoint.
