### ISSUE TITLE
Atualizar playlist do ChatBoss

### ISSUE THREAD

**Issue by emmenezes** [BOSS-BigOpenSourceSister/BigSister#89]
A [playlist do ChatBoss ](https://www.youtube.com/playlist?list=PLFFHHqnY3q2EonAhF5KeIZFPNM40mnmJl) teve sua última atualização no dia 08/09 e desde então houve lançamento de novos vídeos que não foram colocados lá.

Além disso, o primeiro vídeo é privado e poderia ser retirado da playlist.

**Comment by BrunaNayara** [comment]
Atualizei a playlist :D
