### ISSUE TITLE
Problema para colocar labels

### ISSUE THREAD

**Issue by emmenezes** [BOSS-BigOpenSourceSister/BigSister#90]
Fui adicionar uma issue com a @Joranhezon e percebemos que eu não tinha autorização para colocar labels, então pensamos que todas as mentoradas poderiam ser adicionadas ao repositório para ter permissão de editar issues.

**Comment by naiieandrade** [comment]
Pessoal, no `manage access` em `settings`, só tinha a @mariav-flor como *outside collaborator* com papel de *writer*, eu convidei a @emmenezes e agora ela consegue por as labels.

**Comment by Joranhezon** [comment]
@naiieandrade só estava a @mariav-flor porque dei acesso pra que ela pudesse mexer na issue da Talk Like a BOSS, mas acho que vale a pena dar acesso pra todas as little sisters. Cê pode fazer isso?:3

Ai quando fizer pode fechar a issue. :heart:

**Comment by naiieandrade** [comment]
sim @Joranhezon 
A @BrunaNayara já tinha criado um time [little sisters](https://github.com/orgs/BOSS-BigOpenSourceSister/teams/little-sisters), ai coloquei as meninas @emmenezes @giovanadionisio e @mariav-flor lá com o papel de *writer* e já tá funcionando!
Eu não adicionei ainda as outras meninas porque não achei o github delas, tem algum lugar com essas informações? Seria legal, das participantes agora e os seus githubs.

**Comment by naiieandrade** [comment]
Pronto! Adicionei todo mundo @Joranhezon
