### ISSUE TITLE
Sugestão de alteração no padrão de nomes dos vídeos no youtube

### ISSUE THREAD

**Issue by emmenezes** [BOSS-BigOpenSourceSister/BigSister#91]
Eu percebi com os vídeos sobre Actions que algumas coisas podem ficar confusas para quem está começando ou perdeu alguma aula, porque os nomes são muito parecidos e não obrigatoriamente sugerem uma ordem (Actions e python, conteúdo slot e custom action, tutorial custom actions - parte 2, tutorial custom actions - parte 1).

E gostaria de sugerir talvez uma nomeclatura mais repetitiva, mas que deixaria explícita a ordem, colocando sempre a numeração no início, por exemplo:
ChatBoss 1 - O que é Open Source e por que contribuir?
ChatBoss 2 - Entenda o Sistema Operacional Linux e guia de instalação
ChatBoss 3 - Introdução ao Git e contribuição colaborativa

Apesar disso, um problema futuro pode ocorrer se os vídeos forem refeitos e atualizados (por exemplo, existirão dois vídeos chamados 'ChatBoss 1 - O que é Open Source e por que contribuir?') e para solucionar essa nova situação é preciso outra discussão.

Posso sugerir numerar como ChatBoss 1.1, ai a versão seguintes seria a ChatBoss 2.1, ou então colocar o ano e o semestre relativos ao ciclo, ou então adotar algum sistema de código em um estilo bem UnB (CB201, onde CB = Chat Boss, 20 = 2020, 1 = 1º semestre).

Bem, é isso, muito obrigada por lerem o textão kk

**Comment by BrunaNayara** [comment]
@emmenezes adorei a sugestão. 

Coloquei os vídeos na playlist. 
Usei a numeração assim `[ChatBoss Temporada.Semana]`. Seguindo uma das suas sugestões.

Então ficou assim, por exemplo: [ChatBoss 1.1]

**Comment by BrunaNayara** [comment]
Uma coisa que pensei agora foi sobre os tutorias/workshops das tarefas de casa que temos. Acha que vale a pena deixarmos na mesma playlist ou em uma separa apenas pra elas? 

Alguém tem alguma sugestão?

**Comment by emmenezes** [comment]
Ahh eu gostei bastante das alterações, ficou bem claro e fica ótimo na parte de todos os vídeos, porque deixa explícito os tipos de vídeo e suas sequências.

Poderiam ficar na mesma playlist se o nome se referir também à semana e à ordem de exibição. Isso evitaria também várias playlists que tem conteúdos relacionados da mesma temporada.

**Comment by naiieandrade** [comment]
@BrunaNayara tem uma playlist `Chatbot - Tutoriais`, mas não tem nenhum vídeo lá, eu acho legal por as práticas lá. E outra coisa talvez ao final de cada vídeo a gente pode direcionar para outro vídeo, é uma opção fazer isso mesmo que os vídeos estejam em playlist. Eu fiz isso com o do Slot e Custom actions para ir para o Tutorial.

**Comment by BrunaNayara** [comment]
@naiieandrade eu criei a playlist. Hahahaha
Aí depois pensei que seria melhor perguntar aqui pra levantarmos a discussão

Mas acho super válido isso que vc comentou. Outra coisa, é legal ter o link para a prática na descrição do vídeo

**Comment by BrunaNayara** [comment]
Seguindo a sugestão, alterei o nome dos vídeos
