### ISSUE TITLE
Corrigir link das entrevistas

### ISSUE THREAD

**Issue by giovanadionisio** [BOSS-BigOpenSourceSister/BigSister#94]
Alguns links do README da Talk Like a BOSS estão quebrados:
- [ ] Trabalhando com Software Livre (Roteiro)
- [ ] Desenvolvendo jogos na Wildlife (Roteiro)
- [ ] Maratonas de programação (Roteiro)
- [ ] Documentação, escrita técnica e outreachy (Roteiro e Youtube)

**Comment by Joranhezon** [comment]
Obrigada por criar, @giovanadionisio ! :smile_cat:
